# Generated by Django 3.2 on 2021-05-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
