# Generated by Django 3.2 on 2021-05-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0002_alter_usersetting_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='biography',
            field=models.CharField(default='Nothing to see here yet!', max_length=300),
        ),
    ]
